# Generated by Django 5.1.2 on 2025-08-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.CharField(max_length=120)),
                ('discription', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='media_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
