# Generated by Django 5.1.2 on 2025-08-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rule_alter_post_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
    ]
