# Generated by Django 5.1.2 on 2025-08-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_is_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_image',
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video'), ('youtube', 'youtube')], default='image', max_length=10),
        ),
    ]
