# Generated by Django 5.1.2 on 2025-08-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video'), ('youtube', 'youtube')], default='image', max_length=10),
        ),
    ]
