# Generated by Django 5.1.2 on 2025-08-23 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_intended_user_alter_post_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intended_user',
        ),
        migrations.AddField(
            model_name='post',
            name='intended_users',
            field=models.ManyToManyField(blank=True, related_name='posts_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
